import { Home, Building, LayoutDashboard, Wrench, Handshake, Lightbulb } from "lucide-react";

export const services = [
  {
    id: 1,
    title: "Residential Construction",
    description: "Building custom homes and residential estates with precision and care, tailored to your lifestyle.",
    icon: <Home size={32} />,
    link: "/services/1",
    galleryLink: "/projects?category=Residential",
    longDescription: "We specialize in creating bespoke residential properties, from single-family homes to multi-unit estates. Our approach combines innovative design with robust construction techniques, ensuring every home is a sanctuary of comfort and style. We manage every aspect, from foundation to finishes, with meticulous attention to detail.",
    details: [
      "Custom home building",
      "Luxury estate development",
      "Multi-family residential projects",
      "Sustainable and eco-friendly options",
    ],
    cloudinaryId: "kinglaw/services/residential-construction",
    alt: "A modern residential house under construction with a clear blue sky.",
  },
  {
    id: 2,
    title: "Commercial Construction",
    description: "Developing modern commercial spaces, offices, and retail centers designed for functionality and growth.",
    icon: <Building size={32} />,
    link: "/services/2",
    galleryLink: "/projects?category=Commercial",
    longDescription: "Our commercial construction services are designed to deliver high-performance spaces that meet the unique demands of businesses. We build offices, retail outlets, industrial facilities, and hospitality venues, focusing on efficiency, scalability, and aesthetic appeal to support your operational goals.",
    details: [
      "Office buildings and corporate campuses",
      "Retail centers and shopping malls",
      "Industrial facilities and warehouses",
      "Hospitality and leisure developments",
    ],
    cloudinaryId: "kinglaw/services/commercial-construction",
    alt: "The impressive glass facade of a modern commercial skyscraper.",
  },
  {
    id: 3,
    title: "Architectural Design",
    description: "Innovative and functional architectural designs tailored to your vision, blending aesthetics with practicality.",
    icon: <LayoutDashboard size={32} />,
    link: "/services/3",
    galleryLink: "/catalog/designs",
    longDescription: "Our team of experienced architects transforms your ideas into detailed, buildable designs. We prioritize functionality, sustainability, and aesthetic appeal, ensuring that every blueprint reflects your vision while adhering to the highest industry standards. From conceptual sketches to full construction documents, we guide you through every design phase.",
    details: [
      "Conceptual design and feasibility studies",
      "Detailed architectural drawings",
      "3D rendering and visualization",
      "Interior design and space planning",
    ],
    cloudinaryId: "kinglaw/services/architectural-design",
    alt: "An architect reviewing blueprints on a large wooden table.",
  },
  {
    id: 4,
    title: "Renovation & Remodeling",
    description: "Transforming existing structures with modern aesthetics, improved functionality, and sustainable solutions.",
    icon: <Wrench size={32} />,
    link: "/services/4",
    galleryLink: "/gallery",
    longDescription: "Revitalize your existing property with our expert renovation and remodeling services. Whether it's a home update, a commercial space refresh, or a historical restoration, we enhance functionality, modernize aesthetics, and improve energy efficiency, all while preserving the structural integrity and character of the building.",
    details: [
      "Residential renovations and extensions",
      "Commercial space fit-outs",
      "Historical building restoration",
      "Structural modifications and upgrades",
    ],
    cloudinaryId: "kinglaw/services/renovation-remodeling",
    alt: "A newly renovated kitchen with modern appliances and white cabinets.",
  },
  {
    id: 5,
    title: "Project Management",
    description: "Overseeing projects from conception to completion, ensuring efficiency, quality, and adherence to budget.",
    icon: <Handshake size={32} />,
    link: "/services/5",
    galleryLink: "/projects",
    longDescription: "Our comprehensive project management services ensure that your construction project is delivered on time, within budget, and to the highest quality standards. We handle all aspects of coordination, risk management, and stakeholder communication, allowing you to focus on your core business while we manage the complexities of construction.",
    details: [
      "Full project lifecycle management",
      "Budget and schedule control",
      "Risk assessment and mitigation",
      "Contract administration and vendor management",
    ],
    cloudinaryId: "kinglaw/services/project-management",
    alt: "A team of construction managers discussing plans on a tablet at a worksite.",
  },
  {
    id: 6,
    title: "Consultation Services",
    description: "Expert advice and guidance for all your construction and real estate needs, from feasibility to execution.",
    icon: <Lightbulb size={32} />,
    link: "/services/6",
    galleryLink: "/contact",
    longDescription: "Leverage our deep industry knowledge with our expert consultation services. We provide strategic advice on project feasibility, regulatory compliance, cost optimization, and sustainable building practices. Whether you're planning a new development or optimizing an existing one, our insights will guide you to successful outcomes.",
    details: [
      "Feasibility studies and site analysis",
      "Cost estimation and budget planning",
      "Regulatory compliance and permits",
      "Sustainable building and green construction advice",
    ],
    cloudinaryId: "kinglaw/services/consultation-services",
    alt: "A consultant pointing at a chart during a meeting with clients.",
  },
];